apiVersion: apps/v1
kind: Deployment
metadata:
  name: www
spec:
  replicas: NUM_OF_SERVER
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - image: NGINX_IMAGE
        name: www
        ports:
        - containerPort: 80
